### ISSUE TITLE
Implement a message queue

### ISSUE THREAD

**Issue by emersion** [emersion/maddy#11]
This allows for multiple workers and makes sure no message gets lost.

**Comment by foxcpp** [comment]
https://github.com/foxcpp/maddy/tree/queue

**Comment by sapiens-sapide** [comment]
Is it really necessary ? Maddy could still have multiple workers to handle connections. Each workers could wait for the delivery completion before replying `250`. If a worker fails, mail delivery will be uncompleted and client will retry later.  

Not having a filesystem message queue would not only remove complexity from code, it'd also improve privacy ! ;-)

**Comment by emersion** [comment]
What happens if your server hits a power outage? If maddy panics?

**Comment by emersion** [comment]
>Each workers could wait for the delivery completion before replying 250.

Hmm. The reason other systems haven't done this is that it can take quite a while.

**Comment by foxcpp** [comment]
>Each workers could wait for the delivery completion before replying 250. 

I already have seen multiple servers that reject your messages unless you try to submit them multiple times with some delay (hi, postgrey!).

**Comment by sapiens-sapide** [comment]
Are we talking ingress or egress delivery ?

**Comment by foxcpp** [comment]
Egress. For ingress, we already report any errors immediately.

**Comment by emersion** [comment]
I guess this has been implemented in #51?

**Comment by foxcpp** [comment]
Yep.
