### ISSUE TITLE
Add PAM authentication support

### ISSUE THREAD

**Issue by foxcpp** [emersion/maddy#20]
This will allow to reuse a lot of components developed for PAM.

###### Notes
* CGo dependency: libpam
* libpam does have a callback-based interface, it needs to be used with extreme care to not introduce memory vulnerabilities.

###### Problems to solve
* maddy needs to access the shadow database (/etc/shadow) on configurations using the local database. Should we just require maddy to be running as root (or with CAP_DAC_READ_SEARCH) or somehow isolate code working with this file?

Some example code can be found here: https://stackoverflow.com/questions/10910193/how-to-authenticate-username-password-using-pam-w-o-root-privileges
Except probably we want to define our own PAM service instead of using "su".

**Comment by emersion** [comment]
>CGo dependency: libpam

Maybe there is a pure Go libpam wrapper out there? libpam is very annoying to use.

>maddy needs to access the shadow database (/etc/shadow) on configurations using the local database

We don't need that with PAM. We only need that for #21.

**Comment by foxcpp** [comment]
>We don't need that with PAM. We only need that for #21.

From pam_unix.so(8):
>A helper binary, unix_chkpwd(8), is provided to check the user's password when it is stored in a read protected database. This binary is very simple and will only check the password of the user invoking it. It is called transparently on behalf of the user by the authenticating component of this module. In this way it is possible for applications like xlock(1) to work without being setuid-root. The module, by default, will temporarily turn off SIGCHLD handling for the duration of execution of the helper binary.  This is generally the right thing to do, as many applications are not prepared to handle this signal from a child they didn't know was fork()d. The noreap module argument can be used to suppress this temporary shielding and may be needed for use with certain applications.

Ok, didn't knew. Perhaps, can we use it for #21 too?

**Comment by foxcpp** [comment]
Oh, unix_chkpwd works only for current user so it is not useful for us. We need root to access /etc/shadow.

**Comment by foxcpp** [comment]
So, what I think should be done.

Create a separate binary called maddy-pam-helper. 
When started it reads two lines on stdin (username and password) and sets exit status depending on authentication success.

Generally, when installed to the system, this binary should setuid root and be only executable by a group that maddy server runs under (user group "maddy"?).

**Comment by emersion** [comment]
Oh, right. RIP, we need root either way.

**Comment by foxcpp** [comment]
https://github.com/foxcpp/maddy/tree/pam
