### ISSUE TITLE
Add Pure Go local authentication support (Unix)

### ISSUE THREAD

**Issue by foxcpp** [emersion/maddy#21]
Generally, we should try to not introduce a lot of C dependencies (#20). We can implement basic support for local authentication on Unix systems using /etc/passwd and /etc/shadow databases.

**Comment by emersion** [comment]
We need root to read the password DB. We probably need root anyway in case we need to bind to a low port (< 1024)?

(On systems with capabilities support, we can require the cap instead of root for binding to low ports)

**Comment by foxcpp** [comment]
Both this and #20 is implemented on [pam] branch in my fork. 

[pam]: https://github.com/foxcpp/maddy/tree/pam
