### ISSUE TITLE
Replace default files location

### ISSUE THREAD

**Issue by foxcpp** [emersion/maddy#27]
By default configuration should be read from `/etc/maddy/Maddyfile`.
All state (queues, databases) should be stored in `$MADDYPATH` with the default value of `/var/lib/maddy`.

The current implementation is just a placeholder using the current working directory for everything.

**Comment by foxcpp** [comment]
I think we should define `devdirs` build tag to change default directories to make it easier to develop maddy (I really don't like the idea of having testing DB in /var/lib/maddy).

Aux. binaries search path: $MADDYBIN + $GOBIN + $PATH, $MADDYBIN defaults to /usr/libexec/maddy or empty (which means it will use current directory) if devdirs is on.
State directory: $MADDYHOME, defaults to /var/lib/maddy or empty (current directory) if devdirs is on.
Configuration: /etc/maddy/Maddyfile is the main file, imports should be resolved relative to /etc/maddy, i.e. `import foo` will read /etc/maddy/foo.

Non-devdirs values (/usr/libexec/maddy/, /var/lib/maddy, /etc/maddy) are also settable using `-X` linker flag so they can be customized by packagers without the need to patch sources.

@emersion, what do you think?

**Comment by emersion** [comment]
I'm not a big fan of devdirs.

What about defaulting to `/etc/maddy` and providing a flag to override the config file path?

Everything (logfiles path, DB path) should be configurable in the config file anyway. So you could have a dev config file.

>Non-devdirs values (/usr/libexec/maddy/, /var/lib/maddy, /etc/maddy) are also settable using -X linker flag so they can be customized by packagers without the need to patch sources.

+1, this will be required for custom prefixes

**Comment by foxcpp** [comment]
Alright, that makes more sense.
