### ISSUE TITLE
is there any tutorial?

### ISSUE THREAD

**Issue by aguai** [emersion/maddy#4]
where can I find the test mail I sent?
how to set up an account?

**Comment by emersion** [comment]
Maddy is pretty much alpha-quality software and is not ready for general use yet.

It depends how you configured your Maddyfile. With the Maddyfile from the README, the server mirrors another mail server.

--

For people coming from Google: This is very dated reply, currently maddy implements basic functionality of all parts of email stack you expect, including local storage. See README.md for details.
