### ISSUE TITLE
Verify return-path for incoming messages

### ISSUE THREAD

**Issue by foxcpp** [emersion/maddy#41]
Following conditions should be met for verification to pass:
* rDNS domain of source server's IP should be equal to the hostname value presented in EHLO/HELO command
* Hostname domain presented in EHLO/HELO command should resolve to source server's IP address
* Domain in MAIL FROM should have MX record pointing to the source server

These checks are built on the assumption that we have a DNSSEC-enabled resolver and the source server does have DNSSEC enabled.

**Comment by foxcpp** [comment]
I wonder whether we should require rDNS records to be present for the source server. Gmail requires that and so any legitimate and properly configured mail server that wants to work with it (almost all?) should have it.

**Comment by jpsamaroo** [comment]
Counter-argument to requiring rDNS - I run a mailserver at home but my ISP won't configure rDNS since I don't host from a business plan (and they won't let me upgrade to one...). This breaks sending to only a limited number of recipients, and most mailservers seem to not care about rDNS and receive my email just fine.

**Comment by foxcpp** [comment]
Alright, we will leave the rDNS check turned off by default then.

**Comment by foxcpp** [comment]
I wonder if we should define something to run these checks before client sends us a body to not waste traffic on messages that will be rejected anyway.

**Comment by foxcpp** [comment]
@NamedKitten is working on it (~~run and hide, kitten is using git~~)

**Comment by emersion** [comment]
>I wonder if we should define something to run these checks before client sends us a body to not waste traffic on messages that will be rejected anyway.

Should probbaly be done by optimizing the whole pipeline to be streaming instead.
