### ISSUE TITLE
Pre-DATA checks on envelope

### ISSUE THREAD

**Issue by foxcpp** [emersion/maddy#54]
We want to run certain checks (#41) on the envelope before the message body is sent to us to not waste traffic. The current pipeline implementation doesn't allow to run steps before the message body is received.

Also, SMTP doesn't allow us to "abort" transaction once we sent 354 intermediate reply to the DATA command.

I see two possible solutions for this problem:

### Define a special form of checks to be run before the body is sent

Defined somehow like that:
```
smtp ... {
  envelope_checks {
    verify_source_hostname
    verify_source_mx
    ...
  }
}
```

The checks are executed when RCPT/MAIL FROM command received and use the following interface:
```go
type EnvelopeCheck interface {
  CheckFrom(ctx *DeliveryContext, from string) error
  CheckRcpt(ctx *DeliveryContext, rcpt string) error
}
```
Corresponding method is called for each recipient and for source.

#### Advantages

* Ability to report failures per recipient as a status for RCPT TO command.

#### Disadvantages

* See the Advantages of the next method.

### Start pipeline before the body is received

Once the client issues the DATA command, start executing pipeline steps. If any of the steps need the message body - send 354 reply and pass body reader to the pipeline step (with some tricks it can be made fully transparent for step implementation).

#### Advantages

* Uniform interface for all checks
* Conditional checks using pipeline dispatching mechanisms (such as `destination` directive)

#### Disadvantages

* Requires changes to go-smtp (pre-body callback for DATA command)
* It is not possible to report errors for individual recipients or even MAIL FROM command.
  Quoting RFC 5321:
  > Using a "550 mailbox not found" (or
   equivalent) reply code after the data are accepted makes it difficult
   or impossible for the client to determine which recipients failed.

Question regarding standards conformance/interoperability: Are we allowed to return arbitrary failures in the DATA command before the client sends us the body?

**Comment by emersion** [comment]
>Start pipeline before the body is received

+1

>Requires changes to go-smtp (pre-body callback for DATA command)

That's not true, the DATA handler is called before the body has been received (directly after receiving the DATA command). and is given an `io.Reader` that directly reads from the underlying `net.Conn`.

>It is not possible to report errors for individual recipients or even MAIL FROM command.

Hmm. Indeed, that's an issue.

**Comment by foxcpp** [comment]
>That's not true, the DATA handler is called before the body has been received (directly after receiving the DATA command). and is given an io.Reader that directly reads from the underlying net.Conn.

https://github.com/emersion/go-smtp/blob/930d6dfbf447707ddcc38bbafccd8d1596cc6181/conn.go#L435

From my initial post:
>Also, SMTP doesn't allow us to "abort" transaction once we sent 354 intermediate reply to the DATA command.

So at the time DATA handler gets called, we have to consume the body sent by the client, what I want to avoid:
>We want to run certain checks (#41) on the envelope before the message body is sent to us **to not waste traffic**

**Comment by emersion** [comment]
Oh, I see. You're right.

**Comment by foxcpp** [comment]
Still no ideas other/better than n. 1., except probably it is a good idea to split checks:
```
ehlo_checks {
  ...
}
from_checks {
  ...
}
to_checks {
  ....
}
```

**Comment by foxcpp** [comment]
Another (relatively) small change to envelope checks is to hide them behind regular filter directive.
If you, say, write `filter check_source_hostname`, it will actually add a check to the EHLO command. 
But there are several problems with this "attempt to hide complexity": Envelope checks are executed in a different order. Say,  with `filter check_source_mx` and then `filter check_source_mx` user could expect that the checks will run in that order, but in fact, they will be executed in reverse because first "filter" checks RCPT and second checks EHLO. So I proposed to add explicit groups of checks. The same approach used by postifx and it is actually recommended by RFC 5321 (the allowed way is to accept **all** messages and then send bounce messages if something is wrong, but it creates more problems on its own).

**Comment by foxcpp** [comment]
Alright, a decision is needed on this one.

We are going with a modified version of the first solution.
```go
type EhloFilter interface {
  Ehlo(ehlo string) error
}
type FromFilter interface {
  From(to string) (string, error)
}
type RcptFilter interface {
  Rcpt(to string) (string, error)
}
```

```
smtp ... {
  ehlo {
    check_source_hostname
    check_source_rdns
  }
  rcpt {
    check_source_mx
  }
}
```

**Comment by foxcpp** [comment]
Closing in favor of the design change proposed in #101.
