### ISSUE TITLE
Considerations for handling user@domain in username

### ISSUE THREAD

**Issue by foxcpp** [emersion/maddy#57]
**Main Use-Case:** Use different databases for different domains.

**Proposed Solution:** Introduce module `perdomain` that calls different auth. providers depending on the source domain and implement auth. provider interface itself.

```
auth perdomain {
  domain example.org {
    auth virtual { file /etc/maddy/example.org-users }
  }
  domain example.com {
    dont_strip_domain # by default perdomain removes domain from username before passing it to the "nested" provider
    auth virtual { file /etc/maddy/example.com-users }
  }

  # Both make authentication fail by default.
  unknown { # domain not matched by any directives.
    ...
  }
  nodomain { # no domain present in username
    ...
  }
}
```

**Comment by foxcpp** [comment]
Okay, I don't like the initial proposal now. I think we should just strip the local domains before authentication checks.

**Comment by foxcpp** [comment]
So add `auth_allow_domains` directive with string list as an argument.
It can be either set globally or on a per-auth module basis.

Without this directive, only authentication without a domain is permitted.
With this directive, user@domain is allowed if "domain" is from the list. 
Two checks with underlying auth. mechanism are made: `(user@domain, password)` and `(user, password)`. If at least one passes - the user is authenticated.

For SMTP, `AuthDomain` context variable is set. `AuthUser` contains username without domain part.
For IMAP storage, the same two-check logic is used. If account `user@domain` exists - it is used, otherwise, just `user` is tried. Currently, the storage account is created implicitly if authentication succeeded. If storage account doesn't exist, it is created without domain part.

Thoughts?

**Comment by emersion** [comment]
>So add auth_allow_domains directive with string list as an argument.

I like this proposal a lot more. 

>If at least one passes - the user is authenticated.

Hmm, not too keen about this though.

>Currently, the storage account is created implicitly if authentication succeeded.

Looks sane to me

> If storage account doesn't exist, it is created without domain part.

What happens if `user@domain1` and `user@domain2` both login?

**Comment by foxcpp** [comment]
>What happens if user@domain1 and user@domain2 both login?

They get the same storage account ("user") unless either user@domain1 or user@domain2 already exists. 

There is a catch though: if user@domain1 exists but user@domain2 doesn't. First will use storage account with domain and second will use just username.

This makes me think that this logic is flawed and we should just add an option to switch between behaviours (whether or not to strip domain for storage accounts).

**Comment by emersion** [comment]
Yeah, I think an option would be better.

**Comment by foxcpp** [comment]
>Two checks with underlying auth. mechanism are made: (user@domain, password) and (user, password). If at least one passes - the user is authenticated.

I guess option should be added for this too, like `auth_perdomain`.
