### ISSUE TITLE
UTF-8 support?

### ISSUE THREAD

**Issue by Avamander** [emersion/maddy#71]
Just wanted to ask, is every component compatible with internationalized domain names? I'd really like to leave Postfix because it does database connections LATIN-1 only which is rather unusable.

**Comment by foxcpp** [comment]
go-imap-sql doesn't force any encoding options for database connections and handles UTF-8 well by default. I'm not fully confident about how go-imap, go-message and go-smtp handle it tho. @emersion?

**Comment by emersion** [comment]
go-imap should handle UTF-8 properly and transparently encode/decode escaped UTF-8. However, to support other charsets [`imap.CharsetReader`](https://godoc.org/github.com/emersion/go-imap#CharsetReader) should be set (to e.g. go-message's `CharsetReader`).

**Comment by foxcpp** [comment]
So I guess it is correct to say that maddy fully supports UTF-8. Closing as resolved, reopen if you think your question is not fully answered, open a new issue if you have more questions.
