### ISSUE TITLE
SNI support

### ISSUE THREAD

**Issue by Avamander** [emersion/maddy#72]
Just wanted to ask, is there a way to specify that Maddy would serve the right cert based on SNI when using TLS?

**Comment by foxcpp** [comment]
What is your use case? We were talking about it in #58 but decided to leave it out at least for now.

**Comment by foxcpp** [comment]
Duplicate of #58.

**Comment by Avamander** [comment]
Given that MTA-STS is a thing it would be nice to have support for multi-tenant systems for those cases as well.
