### ISSUE TITLE
Subjects and recipients don't show on thunderbird.

### ISSUE THREAD

**Issue by NamedKitten** [emersion/maddy#73]
Steps to reproduce:
1. create user on a fresh, newly-created postgresql db
2. start foxcpp/maddy/master using said db
3. send a email to it with a subject
4. open thunderbird and observe no subject being displayed

**Comment by foxcpp** [comment]
AFAIK, Thunderbird issues the following command to obtain message meta-data.
```
UID FETCH SEQ (UID RFC822.SIZE FLAGS BODY.PEEK[HEADER.FIELDS (From To Cc Bcc Subject Date Message-ID Priority X-Priority References Newsgroups In-Reply-To Content-Type Reply-To)])
```

**Comment by foxcpp** [comment]
Never use maddy from my fork, especially master branch. Please retry with the latest master from this repository.

**Comment by foxcpp** [comment]
```
* 1 FETCH (UID 1 RFC822.SIZE 374 FLAGS (\Recent) BODY[HEADER.FIELDS (FROM TO CC BCC SUBJECT DATE MESSAGE-ID PRIORITY X-PRIORITY REFERENCES NEWSGROUPS IN-REPLY-TO CONTENT-TYPE REPLY-TO)] {2}

)
```
Oh well, it seems like go-imap-sql responds with empty literal for headers.

**Comment by foxcpp** [comment]
Narrowed down to 
```
. UID FETCH * (BODY.PEEK[HEADER.FIELDS (From Content-Type)])
```

**Comment by foxcpp** [comment]
Turns out that go-imap converts header names to upper what makes the following code in backendutil remove all headers from result.
https://github.com/emersion/go-imap/blob/90e8f9c993d935d00617bc1582738e5dca895768/backend/backendutil/body.go#L53-L62

@emesion, is it correct behavior (upper-case conversion for header names)?

**Comment by emersion** [comment]
>go-imap converts header names to upper

Hmm. Not sure why this happens. In nay case, backendutil should compare header keys in a case-insensitive manner.

**Comment by foxcpp** [comment]
@NamedKitten can you confirm that eabdc61 fixes it?
