### ISSUE TITLE
can the author compile for us??

### ISSUE THREAD

**Issue by beanhacker** [emersion/maddy#83]
as when i compile the code, a lot of package needed, some even can not find by myself, and report gcc errors.
as the  idea of go is simple! can you compile for us?
then i wanna make a suggest that can you remove the c++ dependency? as go itself has a lot of dbs in every kind, we just need a exe and optionally a config file. 
thank you!

**Comment by foxcpp** [comment]
>as when i compile the code, a lot of package needed, some even can not find by myself, and report gcc errors.

As far as I know, the only required system dependencies are C compiler and libpam (for maddy-pam-helper, on linux). What is your platform and what gcc errors you are getting?

>then i wanna make a suggest that can you remove the c++ dependency?

Btw, you can disable all C/C++ dependencies by compiling with CGO_ENABLED environment variable set to 0.
```shell
⟩ env CGO_ENABLED=0 go build
⟩ ldd maddy
	not a dynamic executable

⟩ env CGO_ENABLED=1 go build
⟩ ldd maddy
	linux-vdso.so.1 (0x00006f117b956000)
	libdl.so.2 => /usr/lib/libdl.so.2 (0x00006f117b90a000)
	libpthread.so.0 => /usr/lib/libpthread.so.0 (0x00006f117b8e9000)
	libc.so.6 => /usr/lib/libc.so.6 (0x00006f117b724000)
	/lib64/ld-linux-x86-64.so.2 => /usr/lib64/ld-linux-x86-64.so.2 (0x00006f117b957000)
```

Speaking of pre-compiled executables, sure, we will definitely have them for releases (see https://github.com/emersion/maddy/milestone/1). But the current version is not meant to be used by people unless they want to participate in development. I assume if they want - they can figure out how to compile it.

**Comment by beanhacker** [comment]
ohh sorry, my environment before used is blow:
windows 8.1 professional ver, with **X64** architecture.

if you want this project a replacement of other MTA such as postfix, sendmail? then user will only use an pure GO lang exe of maddy to build up their email send && receive environment? to seed all their needs for email? thank you!

**Comment by foxcpp** [comment]
>if you want this project a replacement of other MTA such as postfix, sendmail? then user will only use an pure GO lang exe of maddy to build up their email send && receive environment? to seed all their needs for email? thank you!

Yeah, something like that.

**Comment by foxcpp** [comment]
Anyway, is your problem solved? Reopen if it isn't.
