### ISSUE TITLE
Postgresql storage backend

### ISSUE THREAD

**Issue by emersion** [emersion/maddy#9]

**Comment by foxcpp** [comment]
Started some work here: https://github.com/foxcpp/go-sqlmail/tree/dev.
Maddy fork with it: https://github.com/foxcpp/maddy/tree/sqlmail.

**Comment by emersion** [comment]
Oh that's neat!

**Comment by foxcpp** [comment]
I guess this should be closed because we already have go-imap-sql working and it supports PostgreSQL.
